version: "3.9"

services:
  database:
    image: postgres:14
    restart: unless-stopped
    environment:
      POSTGRES_DB: faucet
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - faucet_db:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  server:
    build:
      context: .
      dockerfile: Dockerfile
    restart: unless-stopped
    depends_on:
      - database
    ports:
      - "5555:5555"
    extra_hosts:
      - "host.docker.internal:host-gateway"

  client:
    build:
      context: ./client
      dockerfile: Dockerfile
    restart: unless-stopped
    environment:
      CONTAINER_ROLE: websocket
    depends_on:
      - database
      - server
    ports:
      - "32790:3000"
    extra_hosts:
      - "host.docker.internal:host-gateway"

volumes:
  faucet_db:
